/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/parbot/ros_workspace/src/parbot_pathplanning/srv/PARbotPathPlanning.srv
 *
 */


#ifndef PARBOT_PATHPLANNING_MESSAGE_PARBOTPATHPLANNINGRESPONSE_H
#define PARBOT_PATHPLANNING_MESSAGE_PARBOTPATHPLANNINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace parbot_pathplanning
{
template <class ContainerAllocator>
struct PARbotPathPlanningResponse_
{
  typedef PARbotPathPlanningResponse_<ContainerAllocator> Type;

  PARbotPathPlanningResponse_()
    : waypoints()
    , pathExists(false)  {
    }
  PARbotPathPlanningResponse_(const ContainerAllocator& _alloc)
    : waypoints(_alloc)
    , pathExists(false)  {
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _waypoints_type;
  _waypoints_type waypoints;

   typedef uint8_t _pathExists_type;
  _pathExists_type pathExists;




  typedef boost::shared_ptr< ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct PARbotPathPlanningResponse_

typedef ::parbot_pathplanning::PARbotPathPlanningResponse_<std::allocator<void> > PARbotPathPlanningResponse;

typedef boost::shared_ptr< ::parbot_pathplanning::PARbotPathPlanningResponse > PARbotPathPlanningResponsePtr;
typedef boost::shared_ptr< ::parbot_pathplanning::PARbotPathPlanningResponse const> PARbotPathPlanningResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace parbot_pathplanning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/hydro/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6905e2db1647286ab28ecaca70d69abc";
  }

  static const char* value(const ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6905e2db1647286aULL;
  static const uint64_t static_value2 = 0xb28ecaca70d69abcULL;
};

template<class ContainerAllocator>
struct DataType< ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "parbot_pathplanning/PARbotPathPlanningResponse";
  }

  static const char* value(const ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] waypoints\n\
bool pathExists\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints);
      stream.next(m.pathExists);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PARbotPathPlanningResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::parbot_pathplanning::PARbotPathPlanningResponse_<ContainerAllocator>& v)
  {
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
    s << indent << "pathExists: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pathExists);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PARBOT_PATHPLANNING_MESSAGE_PARBOTPATHPLANNINGRESPONSE_H
