/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/parbot/ros_workspace/src/roboteq_driver/msg/RoboteqGroupInfo.msg
 *
 */


#ifndef ROBOTEQ_DRIVER_MESSAGE_ROBOTEQGROUPINFO_H
#define ROBOTEQ_DRIVER_MESSAGE_ROBOTEQGROUPINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <roboteq_driver/RoboteqMotorInfo.h>

namespace roboteq_driver
{
template <class ContainerAllocator>
struct RoboteqGroupInfo_
{
  typedef RoboteqGroupInfo_<ContainerAllocator> Type;

  RoboteqGroupInfo_()
    : header()
    , motors()  {
    }
  RoboteqGroupInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , motors(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator> >::other >  _motors_type;
  _motors_type motors;




  typedef boost::shared_ptr< ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct RoboteqGroupInfo_

typedef ::roboteq_driver::RoboteqGroupInfo_<std::allocator<void> > RoboteqGroupInfo;

typedef boost::shared_ptr< ::roboteq_driver::RoboteqGroupInfo > RoboteqGroupInfoPtr;
typedef boost::shared_ptr< ::roboteq_driver::RoboteqGroupInfo const> RoboteqGroupInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboteq_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'roboteq_driver': ['/home/parbot/ros_workspace/src/roboteq_driver/msg'], 'device_driver_base': ['/home/parbot/ros_workspace/devel/share/device_driver_base/msg', '/home/parbot/ros_workspace/src/river_util/device_driver_base/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49d8ecf049aceabf3cbf9a74c09d1c71";
  }

  static const char* value(const ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49d8ecf049aceabfULL;
  static const uint64_t static_value2 = 0x3cbf9a74c09d1c71ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboteq_driver/RoboteqGroupInfo";
  }

  static const char* value(const ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# All of the information for a controller\n\
# index 0 of motors should be channel 1 and index 1 channel 2\n\
\n\
Header header\n\
RoboteqMotorInfo[] motors\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: roboteq_driver/RoboteqMotorInfo\n\
# the current status for a channel on the motor controller\n\
\n\
uint8 channel\n\
float64 position\n\
float64 velocity\n\
float64 current\n\
sensor_msgs/Temperature temp\n\
================================================================================\n\
MSG: sensor_msgs/Temperature\n\
 # Single temperature reading.\n\
\n\
 Header header           # timestamp is the time the temperature was measured\n\
                         # frame_id is the location of the temperature reading\n\
\n\
 float64 temperature     # Measurement of the Temperature in Degrees Celsius\n\
\n\
 float64 variance        # 0 is interpreted as variance unknown\n\
";
  }

  static const char* value(const ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.motors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RoboteqGroupInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboteq_driver::RoboteqGroupInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "motors[]" << std::endl;
    for (size_t i = 0; i < v.motors.size(); ++i)
    {
      s << indent << "  motors[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.motors[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTEQ_DRIVER_MESSAGE_ROBOTEQGROUPINFO_H
