/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/parbot/ros_workspace/src/roboteq_driver/msg/RoboteqMotorInfo.msg
 *
 */


#ifndef ROBOTEQ_DRIVER_MESSAGE_ROBOTEQMOTORINFO_H
#define ROBOTEQ_DRIVER_MESSAGE_ROBOTEQMOTORINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Temperature.h>

namespace roboteq_driver
{
template <class ContainerAllocator>
struct RoboteqMotorInfo_
{
  typedef RoboteqMotorInfo_<ContainerAllocator> Type;

  RoboteqMotorInfo_()
    : channel(0)
    , position(0.0)
    , velocity(0.0)
    , current(0.0)
    , temp()  {
    }
  RoboteqMotorInfo_(const ContainerAllocator& _alloc)
    : channel(0)
    , position(0.0)
    , velocity(0.0)
    , current(0.0)
    , temp(_alloc)  {
    }



   typedef uint8_t _channel_type;
  _channel_type channel;

   typedef double _position_type;
  _position_type position;

   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _current_type;
  _current_type current;

   typedef  ::sensor_msgs::Temperature_<ContainerAllocator>  _temp_type;
  _temp_type temp;




  typedef boost::shared_ptr< ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct RoboteqMotorInfo_

typedef ::roboteq_driver::RoboteqMotorInfo_<std::allocator<void> > RoboteqMotorInfo;

typedef boost::shared_ptr< ::roboteq_driver::RoboteqMotorInfo > RoboteqMotorInfoPtr;
typedef boost::shared_ptr< ::roboteq_driver::RoboteqMotorInfo const> RoboteqMotorInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboteq_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'roboteq_driver': ['/home/parbot/ros_workspace/src/roboteq_driver/msg'], 'device_driver_base': ['/home/parbot/ros_workspace/devel/share/device_driver_base/msg', '/home/parbot/ros_workspace/src/river_util/device_driver_base/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad7e3baf491ed3e6aaae1fd395568d05";
  }

  static const char* value(const ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad7e3baf491ed3e6ULL;
  static const uint64_t static_value2 = 0xaaae1fd395568d05ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboteq_driver/RoboteqMotorInfo";
  }

  static const char* value(const ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# the current status for a channel on the motor controller\n\
\n\
uint8 channel\n\
float64 position\n\
float64 velocity\n\
float64 current\n\
sensor_msgs/Temperature temp\n\
================================================================================\n\
MSG: sensor_msgs/Temperature\n\
 # Single temperature reading.\n\
\n\
 Header header           # timestamp is the time the temperature was measured\n\
                         # frame_id is the location of the temperature reading\n\
\n\
 float64 temperature     # Measurement of the Temperature in Degrees Celsius\n\
\n\
 float64 variance        # 0 is interpreted as variance unknown\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.channel);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.current);
      stream.next(m.temp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RoboteqMotorInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboteq_driver::RoboteqMotorInfo_<ContainerAllocator>& v)
  {
    s << indent << "channel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.channel);
    s << indent << "position: ";
    Printer<double>::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "current: ";
    Printer<double>::stream(s, indent + "  ", v.current);
    s << indent << "temp: ";
    s << std::endl;
    Printer< ::sensor_msgs::Temperature_<ContainerAllocator> >::stream(s, indent + "  ", v.temp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTEQ_DRIVER_MESSAGE_ROBOTEQMOTORINFO_H
