/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/parbot/ros_workspace/src/roboteq_driver/msg/RoboteqGroupMotorControl.msg
 *
 */


#ifndef ROBOTEQ_DRIVER_MESSAGE_ROBOTEQGROUPMOTORCONTROL_H
#define ROBOTEQ_DRIVER_MESSAGE_ROBOTEQGROUPMOTORCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <roboteq_driver/RoboteqMotorControl.h>

namespace roboteq_driver
{
template <class ContainerAllocator>
struct RoboteqGroupMotorControl_
{
  typedef RoboteqGroupMotorControl_<ContainerAllocator> Type;

  RoboteqGroupMotorControl_()
    : motors()  {
    }
  RoboteqGroupMotorControl_(const ContainerAllocator& _alloc)
    : motors(_alloc)  {
    }



   typedef std::vector< ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator> >::other >  _motors_type;
  _motors_type motors;




  typedef boost::shared_ptr< ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct RoboteqGroupMotorControl_

typedef ::roboteq_driver::RoboteqGroupMotorControl_<std::allocator<void> > RoboteqGroupMotorControl;

typedef boost::shared_ptr< ::roboteq_driver::RoboteqGroupMotorControl > RoboteqGroupMotorControlPtr;
typedef boost::shared_ptr< ::roboteq_driver::RoboteqGroupMotorControl const> RoboteqGroupMotorControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboteq_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'roboteq_driver': ['/home/parbot/ros_workspace/src/roboteq_driver/msg'], 'device_driver_base': ['/home/parbot/ros_workspace/devel/share/device_driver_base/msg', '/home/parbot/ros_workspace/src/river_util/device_driver_base/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "702a8e947169b180357862f19d38e10a";
  }

  static const char* value(const ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x702a8e947169b180ULL;
  static const uint64_t static_value2 = 0x357862f19d38e10aULL;
};

template<class ContainerAllocator>
struct DataType< ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboteq_driver/RoboteqGroupMotorControl";
  }

  static const char* value(const ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message to control multiple channels of the controller\n\
\n\
RoboteqMotorControl[] motors\n\
================================================================================\n\
MSG: roboteq_driver/RoboteqMotorControl\n\
# control a single channel of the controller\n\
\n\
# Control Mode Options\n\
uint8 POWER =1\n\
uint8 RPM = 2\n\
uint8 POSITION = 3\n\
\n\
# the channel on the controller to control (1 or 2)\n\
uint8 channel\n\
# how to interpert the setpoint\n\
uint8 control_mode\n\
float64 setpoint\n\
";
  }

  static const char* value(const ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RoboteqGroupMotorControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboteq_driver::RoboteqGroupMotorControl_<ContainerAllocator>& v)
  {
    s << indent << "motors[]" << std::endl;
    for (size_t i = 0; i < v.motors.size(); ++i)
    {
      s << indent << "  motors[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator> >::stream(s, indent + "    ", v.motors[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTEQ_DRIVER_MESSAGE_ROBOTEQGROUPMOTORCONTROL_H
