/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/parbot/ros_workspace/src/roboteq_driver/msg/RoboteqMotorControl.msg
 *
 */


#ifndef ROBOTEQ_DRIVER_MESSAGE_ROBOTEQMOTORCONTROL_H
#define ROBOTEQ_DRIVER_MESSAGE_ROBOTEQMOTORCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboteq_driver
{
template <class ContainerAllocator>
struct RoboteqMotorControl_
{
  typedef RoboteqMotorControl_<ContainerAllocator> Type;

  RoboteqMotorControl_()
    : channel(0)
    , control_mode(0)
    , setpoint(0.0)  {
    }
  RoboteqMotorControl_(const ContainerAllocator& _alloc)
    : channel(0)
    , control_mode(0)
    , setpoint(0.0)  {
    }



   typedef uint8_t _channel_type;
  _channel_type channel;

   typedef uint8_t _control_mode_type;
  _control_mode_type control_mode;

   typedef double _setpoint_type;
  _setpoint_type setpoint;


    enum { POWER = 1 };
     enum { RPM = 2 };
     enum { POSITION = 3 };
 

  typedef boost::shared_ptr< ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct RoboteqMotorControl_

typedef ::roboteq_driver::RoboteqMotorControl_<std::allocator<void> > RoboteqMotorControl;

typedef boost::shared_ptr< ::roboteq_driver::RoboteqMotorControl > RoboteqMotorControlPtr;
typedef boost::shared_ptr< ::roboteq_driver::RoboteqMotorControl const> RoboteqMotorControlConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboteq_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'roboteq_driver': ['/home/parbot/ros_workspace/src/roboteq_driver/msg'], 'device_driver_base': ['/home/parbot/ros_workspace/devel/share/device_driver_base/msg', '/home/parbot/ros_workspace/src/river_util/device_driver_base/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/hydro/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/hydro/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "352e83324a7829eb48c6f1b891ee1520";
  }

  static const char* value(const ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x352e83324a7829ebULL;
  static const uint64_t static_value2 = 0x48c6f1b891ee1520ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboteq_driver/RoboteqMotorControl";
  }

  static const char* value(const ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# control a single channel of the controller\n\
\n\
# Control Mode Options\n\
uint8 POWER =1\n\
uint8 RPM = 2\n\
uint8 POSITION = 3\n\
\n\
# the channel on the controller to control (1 or 2)\n\
uint8 channel\n\
# how to interpert the setpoint\n\
uint8 control_mode\n\
float64 setpoint\n\
";
  }

  static const char* value(const ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.channel);
      stream.next(m.control_mode);
      stream.next(m.setpoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct RoboteqMotorControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboteq_driver::RoboteqMotorControl_<ContainerAllocator>& v)
  {
    s << indent << "channel: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.channel);
    s << indent << "control_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.control_mode);
    s << indent << "setpoint: ";
    Printer<double>::stream(s, indent + "  ", v.setpoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOTEQ_DRIVER_MESSAGE_ROBOTEQMOTORCONTROL_H
