; Auto-generated. Do not edit!


(cl:in-package device_driver_base-msg)


;//! \htmlinclude SetJointPositionResult.msg.html

(cl:defclass <SetJointPositionResult> (roslisp-msg-protocol:ros-message)
  ((final_angle
    :reader final_angle
    :initarg :final_angle
    :type cl:float
    :initform 0.0))
)

(cl:defclass SetJointPositionResult (<SetJointPositionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetJointPositionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetJointPositionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name device_driver_base-msg:<SetJointPositionResult> is deprecated: use device_driver_base-msg:SetJointPositionResult instead.")))

(cl:ensure-generic-function 'final_angle-val :lambda-list '(m))
(cl:defmethod final_angle-val ((m <SetJointPositionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader device_driver_base-msg:final_angle-val is deprecated.  Use device_driver_base-msg:final_angle instead.")
  (final_angle m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetJointPositionResult>) ostream)
  "Serializes a message object of type '<SetJointPositionResult>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'final_angle))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetJointPositionResult>) istream)
  "Deserializes a message object of type '<SetJointPositionResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'final_angle) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetJointPositionResult>)))
  "Returns string type for a message object of type '<SetJointPositionResult>"
  "device_driver_base/SetJointPositionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetJointPositionResult)))
  "Returns string type for a message object of type 'SetJointPositionResult"
  "device_driver_base/SetJointPositionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetJointPositionResult>)))
  "Returns md5sum for a message object of type '<SetJointPositionResult>"
  "93dbf819bceb5218c0e89c45865633a2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetJointPositionResult)))
  "Returns md5sum for a message object of type 'SetJointPositionResult"
  "93dbf819bceb5218c0e89c45865633a2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetJointPositionResult>)))
  "Returns full string definition for message of type '<SetJointPositionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float64 final_angle~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetJointPositionResult)))
  "Returns full string definition for message of type 'SetJointPositionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%float64 final_angle~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetJointPositionResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetJointPositionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SetJointPositionResult
    (cl:cons ':final_angle (final_angle msg))
))
