; Auto-generated. Do not edit!


(cl:in-package device_driver_base-msg)


;//! \htmlinclude SetMotorPositionGoal.msg.html

(cl:defclass <SetMotorPositionGoal> (roslisp-msg-protocol:ros-message)
  ((position
    :reader position
    :initarg :position
    :type cl:integer
    :initform 0)
   (max_velocity
    :reader max_velocity
    :initarg :max_velocity
    :type cl:float
    :initform 0.0))
)

(cl:defclass SetMotorPositionGoal (<SetMotorPositionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetMotorPositionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetMotorPositionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name device_driver_base-msg:<SetMotorPositionGoal> is deprecated: use device_driver_base-msg:SetMotorPositionGoal instead.")))

(cl:ensure-generic-function 'position-val :lambda-list '(m))
(cl:defmethod position-val ((m <SetMotorPositionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader device_driver_base-msg:position-val is deprecated.  Use device_driver_base-msg:position instead.")
  (position m))

(cl:ensure-generic-function 'max_velocity-val :lambda-list '(m))
(cl:defmethod max_velocity-val ((m <SetMotorPositionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader device_driver_base-msg:max_velocity-val is deprecated.  Use device_driver_base-msg:max_velocity instead.")
  (max_velocity m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetMotorPositionGoal>) ostream)
  "Serializes a message object of type '<SetMotorPositionGoal>"
  (cl:let* ((signed (cl:slot-value msg 'position)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'max_velocity))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetMotorPositionGoal>) istream)
  "Deserializes a message object of type '<SetMotorPositionGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'position) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'max_velocity) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetMotorPositionGoal>)))
  "Returns string type for a message object of type '<SetMotorPositionGoal>"
  "device_driver_base/SetMotorPositionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetMotorPositionGoal)))
  "Returns string type for a message object of type 'SetMotorPositionGoal"
  "device_driver_base/SetMotorPositionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetMotorPositionGoal>)))
  "Returns md5sum for a message object of type '<SetMotorPositionGoal>"
  "028e51beb6972c0116064f5b2ead84db")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetMotorPositionGoal)))
  "Returns md5sum for a message object of type 'SetMotorPositionGoal"
  "028e51beb6972c0116064f5b2ead84db")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetMotorPositionGoal>)))
  "Returns full string definition for message of type '<SetMotorPositionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Message representing commanding a motor to a specific position~%#units are device dependant, normally in encoder ticks~%#velocity is in ticks per second~%~%#goal definition~%int32 position~%float32 max_velocity~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetMotorPositionGoal)))
  "Returns full string definition for message of type 'SetMotorPositionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Message representing commanding a motor to a specific position~%#units are device dependant, normally in encoder ticks~%#velocity is in ticks per second~%~%#goal definition~%int32 position~%float32 max_velocity~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetMotorPositionGoal>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetMotorPositionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SetMotorPositionGoal
    (cl:cons ':position (position msg))
    (cl:cons ':max_velocity (max_velocity msg))
))
