; Auto-generated. Do not edit!


(cl:in-package device_driver_base-msg)


;//! \htmlinclude SetMotorPositionResult.msg.html

(cl:defclass <SetMotorPositionResult> (roslisp-msg-protocol:ros-message)
  ((final_position
    :reader final_position
    :initarg :final_position
    :type cl:integer
    :initform 0))
)

(cl:defclass SetMotorPositionResult (<SetMotorPositionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetMotorPositionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetMotorPositionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name device_driver_base-msg:<SetMotorPositionResult> is deprecated: use device_driver_base-msg:SetMotorPositionResult instead.")))

(cl:ensure-generic-function 'final_position-val :lambda-list '(m))
(cl:defmethod final_position-val ((m <SetMotorPositionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader device_driver_base-msg:final_position-val is deprecated.  Use device_driver_base-msg:final_position instead.")
  (final_position m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetMotorPositionResult>) ostream)
  "Serializes a message object of type '<SetMotorPositionResult>"
  (cl:let* ((signed (cl:slot-value msg 'final_position)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetMotorPositionResult>) istream)
  "Deserializes a message object of type '<SetMotorPositionResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'final_position) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetMotorPositionResult>)))
  "Returns string type for a message object of type '<SetMotorPositionResult>"
  "device_driver_base/SetMotorPositionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetMotorPositionResult)))
  "Returns string type for a message object of type 'SetMotorPositionResult"
  "device_driver_base/SetMotorPositionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetMotorPositionResult>)))
  "Returns md5sum for a message object of type '<SetMotorPositionResult>"
  "ab176b822e74d6c47e3016da483f3b23")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetMotorPositionResult)))
  "Returns md5sum for a message object of type 'SetMotorPositionResult"
  "ab176b822e74d6c47e3016da483f3b23")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetMotorPositionResult>)))
  "Returns full string definition for message of type '<SetMotorPositionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 final_position~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetMotorPositionResult)))
  "Returns full string definition for message of type 'SetMotorPositionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 final_position~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetMotorPositionResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetMotorPositionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'SetMotorPositionResult
    (cl:cons ':final_position (final_position msg))
))
