; Auto-generated. Do not edit!


(cl:in-package device_driver_base-msg)


;//! \htmlinclude SetMotorPositionActionGoal.msg.html

(cl:defclass <SetMotorPositionActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type device_driver_base-msg:SetMotorPositionGoal
    :initform (cl:make-instance 'device_driver_base-msg:SetMotorPositionGoal)))
)

(cl:defclass SetMotorPositionActionGoal (<SetMotorPositionActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetMotorPositionActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetMotorPositionActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name device_driver_base-msg:<SetMotorPositionActionGoal> is deprecated: use device_driver_base-msg:SetMotorPositionActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <SetMotorPositionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader device_driver_base-msg:header-val is deprecated.  Use device_driver_base-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <SetMotorPositionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader device_driver_base-msg:goal_id-val is deprecated.  Use device_driver_base-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <SetMotorPositionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader device_driver_base-msg:goal-val is deprecated.  Use device_driver_base-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetMotorPositionActionGoal>) ostream)
  "Serializes a message object of type '<SetMotorPositionActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetMotorPositionActionGoal>) istream)
  "Deserializes a message object of type '<SetMotorPositionActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetMotorPositionActionGoal>)))
  "Returns string type for a message object of type '<SetMotorPositionActionGoal>"
  "device_driver_base/SetMotorPositionActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetMotorPositionActionGoal)))
  "Returns string type for a message object of type 'SetMotorPositionActionGoal"
  "device_driver_base/SetMotorPositionActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetMotorPositionActionGoal>)))
  "Returns md5sum for a message object of type '<SetMotorPositionActionGoal>"
  "f6e1b4938a5ade2a8c1eea0489ba38e4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetMotorPositionActionGoal)))
  "Returns md5sum for a message object of type 'SetMotorPositionActionGoal"
  "f6e1b4938a5ade2a8c1eea0489ba38e4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetMotorPositionActionGoal>)))
  "Returns full string definition for message of type '<SetMotorPositionActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%SetMotorPositionGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: device_driver_base/SetMotorPositionGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Message representing commanding a motor to a specific position~%#units are device dependant, normally in encoder ticks~%#velocity is in ticks per second~%~%#goal definition~%int32 position~%float32 max_velocity~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetMotorPositionActionGoal)))
  "Returns full string definition for message of type 'SetMotorPositionActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%SetMotorPositionGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: device_driver_base/SetMotorPositionGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#Message representing commanding a motor to a specific position~%#units are device dependant, normally in encoder ticks~%#velocity is in ticks per second~%~%#goal definition~%int32 position~%float32 max_velocity~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetMotorPositionActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetMotorPositionActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SetMotorPositionActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
