; Auto-generated. Do not edit!


(cl:in-package device_driver_base-msg)


;//! \htmlinclude SetMotorPositionFeedback.msg.html

(cl:defclass <SetMotorPositionFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback
    :reader feedback
    :initarg :feedback
    :type device_driver_base-msg:MotorFeedback
    :initform (cl:make-instance 'device_driver_base-msg:MotorFeedback)))
)

(cl:defclass SetMotorPositionFeedback (<SetMotorPositionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SetMotorPositionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SetMotorPositionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name device_driver_base-msg:<SetMotorPositionFeedback> is deprecated: use device_driver_base-msg:SetMotorPositionFeedback instead.")))

(cl:ensure-generic-function 'feedback-val :lambda-list '(m))
(cl:defmethod feedback-val ((m <SetMotorPositionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader device_driver_base-msg:feedback-val is deprecated.  Use device_driver_base-msg:feedback instead.")
  (feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SetMotorPositionFeedback>) ostream)
  "Serializes a message object of type '<SetMotorPositionFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'feedback) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SetMotorPositionFeedback>) istream)
  "Deserializes a message object of type '<SetMotorPositionFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'feedback) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SetMotorPositionFeedback>)))
  "Returns string type for a message object of type '<SetMotorPositionFeedback>"
  "device_driver_base/SetMotorPositionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SetMotorPositionFeedback)))
  "Returns string type for a message object of type 'SetMotorPositionFeedback"
  "device_driver_base/SetMotorPositionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SetMotorPositionFeedback>)))
  "Returns md5sum for a message object of type '<SetMotorPositionFeedback>"
  "14cdcffd4f45fd14266ec41b2224084f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SetMotorPositionFeedback)))
  "Returns md5sum for a message object of type 'SetMotorPositionFeedback"
  "14cdcffd4f45fd14266ec41b2224084f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SetMotorPositionFeedback>)))
  "Returns full string definition for message of type '<SetMotorPositionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%device_driver_base/MotorFeedback feedback~%~%~%================================================================================~%MSG: device_driver_base/MotorFeedback~%Header header~%int32 position~%float32 velocity~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SetMotorPositionFeedback)))
  "Returns full string definition for message of type 'SetMotorPositionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%device_driver_base/MotorFeedback feedback~%~%~%================================================================================~%MSG: device_driver_base/MotorFeedback~%Header header~%int32 position~%float32 velocity~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SetMotorPositionFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'feedback))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SetMotorPositionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SetMotorPositionFeedback
    (cl:cons ':feedback (feedback msg))
))
