/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/parbot/ros_workspace/src/parbot_msgs/msg/Command_MSG.msg
 *
 */


#ifndef PARBOT_MSGS_MESSAGE_COMMAND_MSG_H
#define PARBOT_MSGS_MESSAGE_COMMAND_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace parbot_msgs
{
template <class ContainerAllocator>
struct Command_MSG_
{
  typedef Command_MSG_<ContainerAllocator> Type;

  Command_MSG_()
    : command()
    , ID(0)
    , flag(false)
    , value(0.0)
    , emergency(false)  {
    }
  Command_MSG_(const ContainerAllocator& _alloc)
    : command(_alloc)
    , ID(0)
    , flag(false)
    , value(0.0)
    , emergency(false)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _command_type;
  _command_type command;

   typedef int64_t _ID_type;
  _ID_type ID;

   typedef uint8_t _flag_type;
  _flag_type flag;

   typedef double _value_type;
  _value_type value;

   typedef uint8_t _emergency_type;
  _emergency_type emergency;




  typedef boost::shared_ptr< ::parbot_msgs::Command_MSG_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::parbot_msgs::Command_MSG_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Command_MSG_

typedef ::parbot_msgs::Command_MSG_<std::allocator<void> > Command_MSG;

typedef boost::shared_ptr< ::parbot_msgs::Command_MSG > Command_MSGPtr;
typedef boost::shared_ptr< ::parbot_msgs::Command_MSG const> Command_MSGConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::parbot_msgs::Command_MSG_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::parbot_msgs::Command_MSG_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace parbot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'parbot_msgs': ['/home/parbot/ros_workspace/src/parbot_msgs/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::parbot_msgs::Command_MSG_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::parbot_msgs::Command_MSG_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::parbot_msgs::Command_MSG_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::parbot_msgs::Command_MSG_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::parbot_msgs::Command_MSG_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::parbot_msgs::Command_MSG_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::parbot_msgs::Command_MSG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca5c1ee62468a3c53b41da450acbca4f";
  }

  static const char* value(const ::parbot_msgs::Command_MSG_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca5c1ee62468a3c5ULL;
  static const uint64_t static_value2 = 0x3b41da450acbca4fULL;
};

template<class ContainerAllocator>
struct DataType< ::parbot_msgs::Command_MSG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "parbot_msgs/Command_MSG";
  }

  static const char* value(const ::parbot_msgs::Command_MSG_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::parbot_msgs::Command_MSG_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#name of the command being sent mostly for human readability\n\
string command\n\
#ID is optional it allows for multiple listeners to be differentiated (not generated automatically)\n\
int64 ID\n\
#Boolian flag for the message\n\
bool flag\n\
#numeric value if needed\n\
float64 value\n\
#Boolian for emergency stop if False by default\n\
bool emergency\n\
\n\
";
  }

  static const char* value(const ::parbot_msgs::Command_MSG_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::parbot_msgs::Command_MSG_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.ID);
      stream.next(m.flag);
      stream.next(m.value);
      stream.next(m.emergency);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Command_MSG_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::parbot_msgs::Command_MSG_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::parbot_msgs::Command_MSG_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.command);
    s << indent << "ID: ";
    Printer<int64_t>::stream(s, indent + "  ", v.ID);
    s << indent << "flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag);
    s << indent << "value: ";
    Printer<double>::stream(s, indent + "  ", v.value);
    s << indent << "emergency: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emergency);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PARBOT_MSGS_MESSAGE_COMMAND_MSG_H
