/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/parbot/ros_workspace/src/roboteq_mc_nxtgen_driver/srv/CustomCmd.srv
 *
 */


#ifndef ROBOTEQ_MC_NXTGEN_DRIVER_MESSAGE_CUSTOMCMD_H
#define ROBOTEQ_MC_NXTGEN_DRIVER_MESSAGE_CUSTOMCMD_H

#include <ros/service_traits.h>


#include <roboteq_mc_nxtgen_driver/CustomCmdRequest.h>
#include <roboteq_mc_nxtgen_driver/CustomCmdResponse.h>


namespace roboteq_mc_nxtgen_driver
{

struct CustomCmd
{

typedef CustomCmdRequest Request;
typedef CustomCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CustomCmd
} // namespace roboteq_mc_nxtgen_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roboteq_mc_nxtgen_driver::CustomCmd > {
  static const char* value()
  {
    return "3ba8c6f6a1b4f6199817a6ba886503d8";
  }

  static const char* value(const ::roboteq_mc_nxtgen_driver::CustomCmd&) { return value(); }
};

template<>
struct DataType< ::roboteq_mc_nxtgen_driver::CustomCmd > {
  static const char* value()
  {
    return "roboteq_mc_nxtgen_driver/CustomCmd";
  }

  static const char* value(const ::roboteq_mc_nxtgen_driver::CustomCmd&) { return value(); }
};


// service_traits::MD5Sum< ::roboteq_mc_nxtgen_driver::CustomCmdRequest> should match 
// service_traits::MD5Sum< ::roboteq_mc_nxtgen_driver::CustomCmd > 
template<>
struct MD5Sum< ::roboteq_mc_nxtgen_driver::CustomCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roboteq_mc_nxtgen_driver::CustomCmd >::value();
  }
  static const char* value(const ::roboteq_mc_nxtgen_driver::CustomCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboteq_mc_nxtgen_driver::CustomCmdRequest> should match 
// service_traits::DataType< ::roboteq_mc_nxtgen_driver::CustomCmd > 
template<>
struct DataType< ::roboteq_mc_nxtgen_driver::CustomCmdRequest>
{
  static const char* value()
  {
    return DataType< ::roboteq_mc_nxtgen_driver::CustomCmd >::value();
  }
  static const char* value(const ::roboteq_mc_nxtgen_driver::CustomCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roboteq_mc_nxtgen_driver::CustomCmdResponse> should match 
// service_traits::MD5Sum< ::roboteq_mc_nxtgen_driver::CustomCmd > 
template<>
struct MD5Sum< ::roboteq_mc_nxtgen_driver::CustomCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roboteq_mc_nxtgen_driver::CustomCmd >::value();
  }
  static const char* value(const ::roboteq_mc_nxtgen_driver::CustomCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roboteq_mc_nxtgen_driver::CustomCmdResponse> should match 
// service_traits::DataType< ::roboteq_mc_nxtgen_driver::CustomCmd > 
template<>
struct DataType< ::roboteq_mc_nxtgen_driver::CustomCmdResponse>
{
  static const char* value()
  {
    return DataType< ::roboteq_mc_nxtgen_driver::CustomCmd >::value();
  }
  static const char* value(const ::roboteq_mc_nxtgen_driver::CustomCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOTEQ_MC_NXTGEN_DRIVER_MESSAGE_CUSTOMCMD_H
