/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/parbot/ros_workspace/src/parbot_motion_planning/msg/cost_point.msg
 *
 */


#ifndef PARBOT_MOTION_PLANNING_MESSAGE_COST_POINT_H
#define PARBOT_MOTION_PLANNING_MESSAGE_COST_POINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <parbot_motion_planning/cart_point.h>

namespace parbot_motion_planning
{
template <class ContainerAllocator>
struct cost_point_
{
  typedef cost_point_<ContainerAllocator> Type;

  cost_point_()
    : point()
    , cost(0.0)  {
    }
  cost_point_(const ContainerAllocator& _alloc)
    : point(_alloc)
    , cost(0.0)  {
    }



   typedef  ::parbot_motion_planning::cart_point_<ContainerAllocator>  _point_type;
  _point_type point;

   typedef double _cost_type;
  _cost_type cost;




  typedef boost::shared_ptr< ::parbot_motion_planning::cost_point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::parbot_motion_planning::cost_point_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct cost_point_

typedef ::parbot_motion_planning::cost_point_<std::allocator<void> > cost_point;

typedef boost::shared_ptr< ::parbot_motion_planning::cost_point > cost_pointPtr;
typedef boost::shared_ptr< ::parbot_motion_planning::cost_point const> cost_pointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::parbot_motion_planning::cost_point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::parbot_motion_planning::cost_point_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace parbot_motion_planning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/hydro/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'parbot_motion_planning': ['/home/parbot/ros_workspace/src/parbot_motion_planning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::parbot_motion_planning::cost_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::parbot_motion_planning::cost_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::parbot_motion_planning::cost_point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::parbot_motion_planning::cost_point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::parbot_motion_planning::cost_point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::parbot_motion_planning::cost_point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::parbot_motion_planning::cost_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "906deca9fc15cff2ebe26b0d1cb39bb5";
  }

  static const char* value(const ::parbot_motion_planning::cost_point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x906deca9fc15cff2ULL;
  static const uint64_t static_value2 = 0xebe26b0d1cb39bb5ULL;
};

template<class ContainerAllocator>
struct DataType< ::parbot_motion_planning::cost_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "parbot_motion_planning/cost_point";
  }

  static const char* value(const ::parbot_motion_planning::cost_point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::parbot_motion_planning::cost_point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cart_point point\n\
float64 cost\n\
\n\
================================================================================\n\
MSG: parbot_motion_planning/cart_point\n\
float64 x\n\
float64 y\n\
";
  }

  static const char* value(const ::parbot_motion_planning::cost_point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::parbot_motion_planning::cost_point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point);
      stream.next(m.cost);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct cost_point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::parbot_motion_planning::cost_point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::parbot_motion_planning::cost_point_<ContainerAllocator>& v)
  {
    s << indent << "point: ";
    s << std::endl;
    Printer< ::parbot_motion_planning::cart_point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
    s << indent << "cost: ";
    Printer<double>::stream(s, indent + "  ", v.cost);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PARBOT_MOTION_PLANNING_MESSAGE_COST_POINT_H
