/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/parbot/ros_workspace/src/cliff_detection/msg/cliff_status.msg
 *
 */


#ifndef CLIFF_DETECTION_MESSAGE_CLIFF_STATUS_H
#define CLIFF_DETECTION_MESSAGE_CLIFF_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cliff_detection
{
template <class ContainerAllocator>
struct cliff_status_
{
  typedef cliff_status_<ContainerAllocator> Type;

  cliff_status_()
    : cliff_status(0)  {
    }
  cliff_status_(const ContainerAllocator& _alloc)
    : cliff_status(0)  {
    }



   typedef int32_t _cliff_status_type;
  _cliff_status_type cliff_status;




  typedef boost::shared_ptr< ::cliff_detection::cliff_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cliff_detection::cliff_status_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct cliff_status_

typedef ::cliff_detection::cliff_status_<std::allocator<void> > cliff_status;

typedef boost::shared_ptr< ::cliff_detection::cliff_status > cliff_statusPtr;
typedef boost::shared_ptr< ::cliff_detection::cliff_status const> cliff_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cliff_detection::cliff_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cliff_detection::cliff_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cliff_detection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'cliff_detection': ['/home/parbot/ros_workspace/src/cliff_detection/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cliff_detection::cliff_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cliff_detection::cliff_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cliff_detection::cliff_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cliff_detection::cliff_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cliff_detection::cliff_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cliff_detection::cliff_status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cliff_detection::cliff_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f4242e7fe3ea9cc9143523a864bf5d2";
  }

  static const char* value(const ::cliff_detection::cliff_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f4242e7fe3ea9ccULL;
  static const uint64_t static_value2 = 0x9143523a864bf5d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::cliff_detection::cliff_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cliff_detection/cliff_status";
  }

  static const char* value(const ::cliff_detection::cliff_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cliff_detection::cliff_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 cliff_status\n\
";
  }

  static const char* value(const ::cliff_detection::cliff_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cliff_detection::cliff_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cliff_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct cliff_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cliff_detection::cliff_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cliff_detection::cliff_status_<ContainerAllocator>& v)
  {
    s << indent << "cliff_status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cliff_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLIFF_DETECTION_MESSAGE_CLIFF_STATUS_H
