/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/parbot/ros_workspace/src/parbot_pathplanning/srv/PARbotPathPlanning.srv
 *
 */


#ifndef PARBOT_PATHPLANNING_MESSAGE_PARBOTPATHPLANNING_H
#define PARBOT_PATHPLANNING_MESSAGE_PARBOTPATHPLANNING_H

#include <ros/service_traits.h>


#include <parbot_pathplanning/PARbotPathPlanningRequest.h>
#include <parbot_pathplanning/PARbotPathPlanningResponse.h>


namespace parbot_pathplanning
{

struct PARbotPathPlanning
{

typedef PARbotPathPlanningRequest Request;
typedef PARbotPathPlanningResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PARbotPathPlanning
} // namespace parbot_pathplanning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::parbot_pathplanning::PARbotPathPlanning > {
  static const char* value()
  {
    return "9423af04f336496fe4e819f50d02e929";
  }

  static const char* value(const ::parbot_pathplanning::PARbotPathPlanning&) { return value(); }
};

template<>
struct DataType< ::parbot_pathplanning::PARbotPathPlanning > {
  static const char* value()
  {
    return "parbot_pathplanning/PARbotPathPlanning";
  }

  static const char* value(const ::parbot_pathplanning::PARbotPathPlanning&) { return value(); }
};


// service_traits::MD5Sum< ::parbot_pathplanning::PARbotPathPlanningRequest> should match 
// service_traits::MD5Sum< ::parbot_pathplanning::PARbotPathPlanning > 
template<>
struct MD5Sum< ::parbot_pathplanning::PARbotPathPlanningRequest>
{
  static const char* value()
  {
    return MD5Sum< ::parbot_pathplanning::PARbotPathPlanning >::value();
  }
  static const char* value(const ::parbot_pathplanning::PARbotPathPlanningRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::parbot_pathplanning::PARbotPathPlanningRequest> should match 
// service_traits::DataType< ::parbot_pathplanning::PARbotPathPlanning > 
template<>
struct DataType< ::parbot_pathplanning::PARbotPathPlanningRequest>
{
  static const char* value()
  {
    return DataType< ::parbot_pathplanning::PARbotPathPlanning >::value();
  }
  static const char* value(const ::parbot_pathplanning::PARbotPathPlanningRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::parbot_pathplanning::PARbotPathPlanningResponse> should match 
// service_traits::MD5Sum< ::parbot_pathplanning::PARbotPathPlanning > 
template<>
struct MD5Sum< ::parbot_pathplanning::PARbotPathPlanningResponse>
{
  static const char* value()
  {
    return MD5Sum< ::parbot_pathplanning::PARbotPathPlanning >::value();
  }
  static const char* value(const ::parbot_pathplanning::PARbotPathPlanningResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::parbot_pathplanning::PARbotPathPlanningResponse> should match 
// service_traits::DataType< ::parbot_pathplanning::PARbotPathPlanning > 
template<>
struct DataType< ::parbot_pathplanning::PARbotPathPlanningResponse>
{
  static const char* value()
  {
    return DataType< ::parbot_pathplanning::PARbotPathPlanning >::value();
  }
  static const char* value(const ::parbot_pathplanning::PARbotPathPlanningResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PARBOT_PATHPLANNING_MESSAGE_PARBOTPATHPLANNING_H
